<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dharma.Shared\Dharma.Shared.csproj" />
    <ProjectReference Include="..\Identity\Infrastructure\Dharma.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Customer\Application\Dharma.Customer.Application.csproj" />
    <ProjectReference Include="..\Customer\Domain\Dharma.Customer.Domain.csproj" />
    <ProjectReference Include="..\Order\Application\Dharma.Order.Application.csproj" />
    <ProjectReference Include="..\Order\Domain\Dharma.Order.Domain.csproj" />
    <ProjectReference Include="..\PoojaSamagri\Application\Dharma.PoojaSamagri.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.20">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
