<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\Dharma.Delivery.Application.csproj" />
    <ProjectReference Include="..\Domain\Dharma.Delivery.Domain.csproj" />
    <ProjectReference Include="..\..\Dharma.Shared\Dharma.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
