// <auto-generated />
using System;
using Dharma.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dharma.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DharmaDbContext))]
    [Migration("20260910150149_IdentityFoundation")]
    partial class IdentityFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentityOtpChallengeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("ResendAvailableAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNormalized", "CreatedAt");

                    b.HasIndex("State", "ExpiresAt");

                    b.ToTable("otp_challenges", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentityRefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("FamilyId", "ExpiresAt");

                    b.ToTable("refresh_token_nodes", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentitySessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "State");

                    b.HasIndex("UserId", "State", "LastSeenAt");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentityUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneLookupHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PhoneNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneLookupHash")
                        .IsUnique();

                    b.HasIndex("PhoneNormalized")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.InboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Consumer")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventId", "Consumer");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.OutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "OccurredAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentityRefreshTokenRecord", b =>
                {
                    b.HasOne("Dharma.Infrastructure.Persistence.IdentitySessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dharma.Infrastructure.Persistence.IdentitySessionRecord", b =>
                {
                    b.HasOne("Dharma.Infrastructure.Persistence.IdentityUserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
